name: test

# Run on pull requests and on the master branch itself.
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:


jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the code.
      - uses: actions/checkout@v4
      # Activate python environment
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: build
        run: make install
      - name: test
        run: make test
      - name: create packages
        run: bin/python setup.py sdist bdist_wheel
      # - name: coverage report
      #   run: bin/coveralls
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Publish package
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
